[package]
name = "emojicp"
version = "0.1.0"
edition = "2021"
authors = ["Nicholas R. Smith"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
termion = "2.0.1"
arboard = "3.2.0"
bk-tree = { git = "https://github.com/johnDeSilencio/rust-bk-tree", branch = "feature/serde_support" }
serde = { version = "1.0.152", features = ["derive"] }
bincode = "1.3"
